// Aveiro places (Portuguese coastal city, famous for canals, salt pans, art nouveau).
// Coordinates are normalized 0..1 within the stylized map.

const PLACES = [
  {
    id: 'p1',
    name: 'Praça do Peixe',
    address: 'Rua das Olarias',
    desc: 'Lugar amplo junto à esplanada, com rebaixe de passeio e piso plano em calçada nivelada.',
    distance: '180 m',
    rating: 4.8,
    reviews: 24,
    addedBy: 'Marta R.',
    addedAgo: 'há 3 dias',
    x: 0.36, y: 0.42,
    available: true,
  },
  {
    id: 'p2',
    name: 'Mercado Manuel Firmino',
    address: 'Largo do Rossio, 1',
    desc: 'Dois lugares marcados na entrada norte. Acesso direto ao mercado sem degraus.',
    distance: '320 m',
    rating: 4.6,
    reviews: 41,
    addedBy: 'Câmara Municipal',
    addedAgo: 'há 2 semanas',
    x: 0.48, y: 0.55,
    available: true,
  },
  {
    id: 'p3',
    name: 'Estação CP Aveiro',
    address: 'Av. Dr. Lourenço Peixinho',
    desc: 'Quatro lugares na zona de embarque rápido. Próximo do elevador da estação.',
    distance: '650 m',
    rating: 4.9,
    reviews: 87,
    addedBy: 'João M.',
    addedAgo: 'há 1 mês',
    x: 0.72, y: 0.34,
    available: true,
  },
  {
    id: 'p4',
    name: 'Forum Aveiro',
    address: 'Rua Batalhão Caçadores 10',
    desc: 'Parque coberto com vagas dedicadas no piso 0, perto dos elevadores principais.',
    distance: '430 m',
    rating: 4.4,
    reviews: 56,
    addedBy: 'Inês P.',
    addedAgo: 'há 5 dias',
    x: 0.42, y: 0.30,
    available: true,
  },
  {
    id: 'p5',
    name: 'Universidade de Aveiro',
    address: 'Campus de Santiago',
    desc: 'Vagas ao longo do edifício do reitorado, perto da entrada acessível.',
    distance: '1.2 km',
    rating: 4.7,
    reviews: 33,
    addedBy: 'AAUAv',
    addedAgo: 'há 2 meses',
    x: 0.65, y: 0.72,
    available: false,
  },
  {
    id: 'p6',
    name: 'Cais dos Botirões',
    address: 'Canal Central',
    desc: 'Junto ao embarcadouro dos moliceiros. Rampa de acesso ao passeio em betão.',
    distance: '240 m',
    rating: 4.5,
    reviews: 19,
    addedBy: 'Pedro S.',
    addedAgo: 'há 1 semana',
    x: 0.28, y: 0.50,
    available: true,
  },
  {
    id: 'p7',
    name: 'Largo da Sé',
    address: 'Rua João Mendonça',
    desc: 'Um lugar encostado ao adro. Calçada portuguesa, irregular em troços.',
    distance: '510 m',
    rating: 4.1,
    reviews: 12,
    addedBy: 'Helena C.',
    addedAgo: 'há 4 dias',
    x: 0.55, y: 0.62,
    available: true,
  },
  {
    id: 'p8',
    name: 'Centro de Saúde',
    address: 'Av. 25 de Abril',
    desc: 'Três vagas reservadas em frente à entrada principal. Iluminação nocturna.',
    distance: '880 m',
    rating: 4.9,
    reviews: 64,
    addedBy: 'ARS Centro',
    addedAgo: 'há 1 mês',
    x: 0.20, y: 0.30,
    available: true,
  },
];

const FILTERS = [
  { id: 'near',    label: 'Próximos' },
  { id: 'recent',  label: 'Recentes' },
  { id: 'avail',   label: 'Disponíveis' },
];

Object.assign(window, { PLACES, FILTERS });
